version: "3"
services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/hackacode
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "hackacode"
      MYSQL_USER: "hackacode"
      MYSQL_PASSWORD: "hackacode"
      MYSQL_ROOT_PASSWORD: "123"

volumes:
  mysql-data:
    external: false
