version: "3.9"
services:
#new app (angular_app)
#  angular_app:
#    container_name: angular_app
#    image: pee-angular_app:1.0.0
#    build: ./webapp/
#    ports:
#      - 4200:4200
#    depends_on:
#      - app
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/hackacode
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "hackacode"
      MYSQL_USER: "hackacode"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"

volumes:
  mysql-data:
    external: false
